#!/bin/bash

# Usage: antisleep [time]
# time is in hours
# if no args then 1h is assumed

if [ -n $1 ]; then
	TIME=$(( $1 * 3600 ))
else
	TIME=3600
fi

TIME_LEFT=$TIME
TIME_INT=$(( $TIME / 10 ))

xset s off
xset -dpms
echo "DPMS off..."

for i in {1..10}
do
	echo "sleeping for $(( $TIME_LEFT / 60))m..."
	sleep $TIME_INT
	TIME_LEFT=$(( $TIME_LEFT - $TIME_INT ))
done

xset s on
xset +dpms
echo "DPMS on..."

echo "exiting :->"
